# -*- coding: utf-8 -*-
"""SentenceSimilarity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tb975QxkCqO3CU4MNwIV6HWe2uqjBv_D
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter the first text: ")
text2=input("Enter the second text: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\nSimilarity Score:",round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")
  _

from sentence_transformers import SentenceTransformer, util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter the first text: ")
text2=input("Enter the second text: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\nSimilarity Score:",round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")

from sentence_transformers import SentenceTransformer, util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter the first text: ")
text2=input("Enter the second text: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("\nSimilarity Score:",round(float(similarity),2))
if similarity > 0.75:
  print("Similarity Level: High")
elif similarity > 0.4:
  print("Similarity Level: Medium")
else:
  print("Similarity Level: Low")